[package]
name = "kairos"
version = "0.0.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "A library on top of chrono to calculate times and dates ergonomically"

categories  = [ "date-and-time" ]
keywords    = ["time", "calc", "parser"]
readme      = "README.md"
license     = "MPL-2.0"

repository    = "https://github.com/matthiasbeyer/kairos"

[dependencies]
chrono = "0.4"
error-chain = "0.10"
nom = "3.2"
iso8601 = { git = "https://github.com/matthiasbeyer/iso8601", branch = "update-nom" }

filters = { version  = "0.1.1", optional = true }

[dev-dependencies]
env_logger = "0.4"
log        = "0.3"

[features]
default = []
with-filters = [ "filters" ]

